version: "3.9"
# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-env: &env
  environment:
    - PUID=1031
    - PGID=100
    - UMASK_SET=022
    - TZ=America/Los_Angeles
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    <<: *env
    volumes:
      - /volume1/docker/radarr-config:/config
      - /volume2/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    <<: *env
    volumes:
      - /volume2/data/usenet:/data/usenet
      - /volume1/docker/sabnzbd-config:/config
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    <<: *env
    volumes:
      - /volume1/docker/bazarr-config:/config
      - /volume2/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    <<: *env
    volumes:
      - /volume1/docker/sonarr-config:/config
      - /volume2/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    volumes:
      - ./notifiarr.conf:/config/notifiarr.conf
    ports:
      - 5454:5454
    hostname: Dumpster
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    <<: *env
    volumes:
      - ./calibre-data:/config
    ports:
      - 18080:8080
      - 18081:8081
    restart: unless-stopped
  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    <<: *env
    volumes:
      - ./readarr-data:/config
      - /volume2/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped
