---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./public/assets:/www/assets
    ports:
      - 2080:8080
    environment:
      # For rootless Docker
      - UID=0
      - GID=0
    restart: unless-stopped
